---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  centos-5-x64:
    platform: el-5-x86_64
    hypervisor: docker
    image: centos:5
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which'
      - 'sed -i -e "/mingetty/d" /etc/inittab'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
