---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  debian-7-x64:
    platform: debian-7-amd64
    hypervisor: docker
    image: debian:7
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'echo deb http://ftp.debian.org/debian wheezy-backports main >> /etc/apt/sources.list'
      - 'apt-get update && apt-get install -y cron locales-all net-tools wget'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
