---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  ubuntu-1604-x64:
    platform: ubuntu-16.04-amd64
    hypervisor: docker
    image: ubuntu:16.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y net-tools wget locales'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  trace_limit: 200
  masterless: true
...
# vim: syntax=yaml
