fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.6.0"
    ruby:    "git://github.com/puppetlabs/puppetlabs-ruby.git"
    gcc:     "git://github.com/puppetlabs/puppetlabs-gcc.git"
    pe_gem:  "git://github.com/puppetlabs/puppetlabs-pe_gem.git"
    make:    "git://github.com/cmroddy/puppet-make.git"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile.git"
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    git:     "git://github.com/puppetlabs/puppetlabs-git.git"
    portage: "git://github.com/gentoo/puppet-portage.git"
  symlinks:
    r10k:    "#{source_dir}"
