fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    choria: https://github.com/choria-io/puppet-choria.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    git: https://github.com/puppetlabs/puppetlabs-git.git
    inifile: https://github.com/puppetlabs/puppetlabs-inifile.git
    mcollective: https://github.com/choria-io/puppet-mcollective.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
    vcsrepo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  forge_modules:
    mcollective_agent_filemgr: "choria/mcollective_agent_filemgr"
    mcollective_agent_package: "choria/mcollective_agent_package"
    mcollective_agent_puppet: "choria/mcollective_agent_puppet"
    mcollective_agent_service: "choria/mcollective_agent_service"
    mcollective_choria: "choria/mcollective_choria"
    mcollective_util_actionpolicy: "choria/mcollective_util_actionpolicy"
