---
.travis.yml:
  secure: "ZKiuoKHwvOV4NP0D1iZfxQ2WKQs2QRkoaKviIoT96AjaTuqdYQ7JKr7YNr/AP+V7HeIpwubKbxzJjRpRDLWAB+pOEM7Uguz3hX+KuHjGBlRcfeOfamWj3SFFZomf2LiCXWME1Rv/6qmpCqr49ZZk9ANkSDIvkhuSc/uj0/Tf8o4="
spec_overrides:
  - "add_custom_fact :pe_version, '2016.4.2'"
